-- Add missing soft delete columns to RecurringInvoices and RecurringInvoiceLines tables
-- These columns are part of AuditableEntity but were missing from the database

-- RecurringInvoices table
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RecurringInvoices' AND COLUMN_NAME = 'DeletedAt')
BEGIN
    ALTER TABLE RecurringInvoices ADD DeletedAt DATETIME2 NULL;
END

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RecurringInvoices' AND COLUMN_NAME = 'DeletedBy')
BEGIN
    ALTER TABLE RecurringInvoices ADD DeletedBy UNIQUEIDENTIFIER NULL;
END

-- RecurringInvoiceLines table
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RecurringInvoiceLines' AND COLUMN_NAME = 'DeletedAt')
BEGIN
    ALTER TABLE RecurringInvoiceLines ADD DeletedAt DATETIME2 NULL;
END

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RecurringInvoiceLines' AND COLUMN_NAME = 'DeletedBy')
BEGIN
    ALTER TABLE RecurringInvoiceLines ADD DeletedBy UNIQUEIDENTIFIER NULL;
END

-- WebCustomers table - missing profile columns
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'WebCustomers' AND COLUMN_NAME = 'AvatarUrl')
BEGIN
    ALTER TABLE WebCustomers ADD AvatarUrl NVARCHAR(500) NULL;
END

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'WebCustomers' AND COLUMN_NAME = 'DateOfBirth')
BEGIN
    ALTER TABLE WebCustomers ADD DateOfBirth DATE NULL;
END

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'WebCustomers' AND COLUMN_NAME = 'PasswordResetToken')
BEGIN
    ALTER TABLE WebCustomers ADD PasswordResetToken NVARCHAR(200) NULL;
END

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'WebCustomers' AND COLUMN_NAME = 'PasswordResetExpiry')
BEGIN
    ALTER TABLE WebCustomers ADD PasswordResetExpiry DATETIME2 NULL;
END

-- WebOrders table - missing order columns
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'WebOrders' AND COLUMN_NAME = 'CancelReason')
BEGIN
    ALTER TABLE WebOrders ADD CancelReason NVARCHAR(500) NULL;
END

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'WebOrders' AND COLUMN_NAME = 'CancelledAt')
BEGIN
    ALTER TABLE WebOrders ADD CancelledAt DATETIME2 NULL;
END

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'WebOrders' AND COLUMN_NAME = 'Currency')
BEGIN
    ALTER TABLE WebOrders ADD Currency NVARCHAR(10) NULL DEFAULT 'USD';
END

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'WebOrders' AND COLUMN_NAME = 'Notes')
BEGIN
    ALTER TABLE WebOrders ADD Notes NVARCHAR(MAX) NULL;
END

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'WebOrders' AND COLUMN_NAME = 'ShippingPhone')
BEGIN
    ALTER TABLE WebOrders ADD ShippingPhone NVARCHAR(50) NULL;
END

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'WebOrders' AND COLUMN_NAME = 'TaxRate')
BEGIN
    ALTER TABLE WebOrders ADD TaxRate DECIMAL(18,4) NULL DEFAULT 0;
END

PRINT 'Missing columns added successfully';
